Controllers films users
IvanSuchilin/java-filmorate pull request #1
Opened 2022-09-15 13:26 UTC by IvanSuchilin

Added controllers and validation tests

2022-09-16 13:38 UTC, Fleaman777 requested changes

2022-09-16 13:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidBirthdateException.java
> +public class InvalidBirthdateException extends RuntimeException {
с одной стороны хорошо, когда есть специфическое исключение, по которому можно понять, что пошло не так, 
но с другой, если на каждый невалидный случай делать свое искл., их в какой-то момент может развестись очень много, что будет только больше путать, чем помогать, 

поэтому можно было создать 1 исключение, например ValidationException 
и передавать в него разные сообщения ошибки

2022-09-16 13:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        void validateFilm(Film film){
хорошая, подробная валидация, понятно в чем именно не правильный запрос,
и здорово, что она в отдельном методе, 

потом, ее будет проще переместить в отдельный валидационный класс(спринг компонент)

если есть время и желание, можешь например, уже сейчас попробовать это сделать

2022-09-16 13:38 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidDescriptionLengthException.java
> +public class InvalidDescriptionLengthException extends RuntimeException {
как еще один вариант для исключения, 
наследоваться от ResponseStatusException 
это специадльное исключение, которое позволяет задать подходящий http error code, 
в случае, непройденной валидации, клиент получит соответствующий еррор код и сообщение ошиюки

2022-09-16 13:38 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                        "Свободные народы Средиземья для противостояния армиям Саурона в Войне Кольца.")
лучше описание вынести в отдельную константу, 
так тест будет восприниматься легче

2022-09-16 13:38 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .build();
получение фильма можно было бы вынести в отдельный метод с соответствующими аргументами, 
так часть дублирующей логики будете в одном общем месте

аналагично и для юзерконтроллера

2022-09-16 13:38 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                () -> filmController.validateFilm(film));
В enterprise приложениях на java, особенно написанных на Spring, в ....ControllerTest обычно тестируется api - на контроллер приходят определенные запросы(это делается специальной сущностью, а не просто вызывается эндпоинт метод), приложение полностью все отрабатывает, и затем отвечает определенным кодом и response body, которые и проверяются - такие тесты называются интеграционными. им ты научишься чуть позже

Валидацию хорошо тестировать в обычных юнит тестах. Как раз, это будет проще сделать, если ее вынести в отдельный класс в отдельной директории.

этот комментарий тоже больше для информации,
если вдруг решишь часть валидации вынести в отдельный класс, можешь частично реализовать этот подход

2022-09-18 10:54 UTC, IvanSuchilin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                        "Свободные народы Средиземья для противостояния армиям Саурона в Войне Кольца.")
Done

2022-09-18 17:54 UTC, IvanSuchilin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .build();
Done

2022-09-18 17:55 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidDescriptionLengthException.java
> +public class InvalidDescriptionLengthException extends RuntimeException {
Done

2022-09-18 17:55 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/exception/InvalidBirthdateException.java
> +public class InvalidBirthdateException extends RuntimeException {
Done with ResponseStatusException

2022-09-18 17:55 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        void validateFilm(Film film){
Вынес валидацию за пределы контроллеров

2022-09-18 17:56 UTC, IvanSuchilin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                () -> filmController.validateFilm(film));
Так как вынес валидацию в отдельный класс -оставил тесты для валидации, а не для контроллеров

2022-09-19 18:12 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        void validateFilm(Film film){
отлично, молодец, что решил этому уделить время

2022-09-19 18:20 UTC, Fleaman777 approved these changes

2022-09-19 18:20 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    Validation validation = new Validation();
поле можно сделать private

2022-09-19 18:20 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/validation/ValidationTest.java
> +    Validation validation = new Validation();
здесь validation тоже можно сделать private, 
а его инициализацию хорошо было бы сделать в методе с аннотацией BeforeEach, 
так, в будущем, будет проще изменять,добавлять всякую необходимую инициализационную логику для тестов

2022-09-19 19:11 UTC, merged