Add friends likes
IvanSuchilin/java-filmorate pull request #2
Opened 2022-10-02 15:38 UTC by IvanSuchilin

2022-10-03 16:03 UTC, Fleaman777 requested changes

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Integer id;
не ошибка, но просто как еще один вариан реализации,

айдишники хорошо еще делать в виде типа Long, в случае, если наше приложение будет сильно разрастаться, можно много дольше быть уверенным, что уникальные айдишники не закончатся

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        }
логику этоого if можно было бы вынести в отдельный метод,
 и применять его в местах где нужная такая проверка

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Map<Integer, User> actualUsers = userStorage.getUsers();
сейчас, такая логика еще допускается: логику получения, всех юзеров/фильмов,  проверка есть ли определнный элемент и его получение, 

но в целом, ее можно было бы улучшить: иметь специальный метод в репозитории getById(id), который как раз будет покрывать все перечисленные чуть выше шаги

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +                .collect(Collectors.toList());
отличный стрим, 

но можно результат этого стрима filmStorage.getFilms().values()) не передавать в конструктор ArrayList, а сразу его использовать, т.е. 

```
         return filmStorage.getFilms().values().stream()
                .sorted(Comparator.comparing(Film::getRate).reversed())
                .limit(count)
                .collect(Collectors.toList());
```

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        }
аналагично с FilmService

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        }
логика, которая сейчас написана в циклах for, 
можно было бы переделать на стрим формат, 
с использованием методов filter и foreach

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        log.debug("Получен запрос GET /users/{id}/friends/common/{otherId}.");
если писать такой лог, то лучше его делать в контроллере, 
т.к. в теории, этот метож может использоваться не из UserController, 
а из каких-нибудь других сервисов или контроллеров, тогда получится, что выведенная информация в лог будет не совсем корректной

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        }
этот форич хорошо было бы сделать через стрим

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +}
удобно было бы добавить метод getById(id)

2022-10-03 16:03 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
на самом деле, не совсем обязательный эксепшен хендлер, 
т.к. если в сервисе случается какая-та ошибка, то сервис как раз выбросит 500 код,

2022-10-03 20:44 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Integer id;
done

2022-10-03 20:45 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        }
done: перенес в новый метод получения по id

2022-10-03 20:45 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +        Map<Integer, User> actualUsers = userStorage.getUsers();
done: перенес в новый метод получения по id

2022-10-03 20:46 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
> +                .collect(Collectors.toList());
done

2022-10-03 20:46 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        }
done: перенес в новый метод получения по id

2022-10-03 20:49 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        log.debug("Получен запрос GET /users/{id}/friends/common/{otherId}.");
done: перенес лог

2022-10-03 20:49 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +}
done

2022-10-03 20:50 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    public ErrorResponse handleThrowable(final Throwable e) {
done: убрал

2022-10-03 21:00 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        }
done

2022-10-04 11:55 UTC, IvanSuchilin commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        }
Я не совсем понимаю как применить тут стрим для изменения в "базе данных"
Сократил код, используя методы коллекции

2022-10-04 13:57 UTC, Fleaman777 approved these changes

2022-10-04 13:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Long id;
отлично, молодец, 
что сразу решил приобщаться к хорошим практикам :)

2022-10-04 13:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +        }
ну да, перепроверил, попробовал написать через стрим, не получилось, с 1 взгляда показалось, что он здесь хорошо применится,
так что, ты сделал все правильно :)

2022-10-04 13:57 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
>          log.debug("Получен запрос GET /users/{id}");
здесь тоже, можно было бы перместить лог в контроллер

2022-10-04 13:57 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/validation/ValidationTest.java
> +                .id(1L)
отлично, тесты отработали как положено)
упали тогда, когда были структурные изменения в приложении

2022-10-18 20:04 UTC, merged